spring:
    datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://localhost:3306/boot-blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
       username: root
       password: 123123123
    data:
      redis:
        # ??
        host: 43.142.255.148
        # ??????6379
        port: 6379
        # ?????
        database: 0
        # ??
        #    password:
        # ??????
        timeout: 10s
        lettuce:
          pool:
            # ???????????
            min-idle: 0
            # ???????????
            max-idle: 8
            # ????????????
            max-active: 8
            # #???????????????????????
            max-wait: -1ms

# MyBatis????
mybatis:
    mapper-locations: classpath:mapper/*.xml
